spring.application.name=open_feign_client

# This is where the OpenFeign client functionality is exposed
server.port=9090

# This is the REST endpoint that OpenFeign consumes.
name.service.url=http://localhost:8080