spring.application.name=webclient_example

# This is where the WebClient Consumer functionality is exposed
server.port=9090

# This is the REST endpoint that WebClient consumes.
name.service.url=http://localhost:8080